### DISCUSSION TITLE
cl-rest-config.json gets overwritten using Docker Image

### DISCUSSION THREAD

**Discussion by timmornYE** [Ride-The-Lightning/c-lightning-REST#171] [General]
Using the Docker Image provided at https://hub.docker.com/r/saubyk/c-lightning-rest `cl-rest-config.json` always gets overwritten by the default

```bash
{
"PORT": 3001,
"DOCPORT": 4001,
"PROTOCOL": "https",
"EXECMODE": "production",
"RPCCOMMANDS": ""
}
```

every time I start the container. Tried to make an own image where I keep care that my config is there from beginning. But no matter what I do... it always gets replaced by default. I do not think this is desired behaviour?

**Comment by ShahanaFarooqui** [comment]
Did you try [mounting](https://docs.docker.com/storage/volumes/) the config to your container?

**Comment by timmornYE** [comment]
Yes. Did both to be sure.

c-lightning-rest.dockerfile:

```
FROM saubyk/c-lightning-rest:0.10.2

COPY ./c-lightning-rest/cl-rest-config.json /usr/src/app/cl-rest-config.json
```

docker-compose.yaml

```
  c-lightning-rest:
    image: c-lightning-rest
    volumes:
      - ./c-lightning-rest/cl-rest-config.json:/usr/src/app/cl-rest-config.json
      - ./lightning/:/root/.lightning/
      - ./c-lightning-rest/certs/:/usr/src/app/certs/
    ports:
      - 3001:3001
    depends_on: 
      - lightningd
    build:
      context: .
      dockerfile: c-lightning-rest.dockerfile
```
